<?php
/**
 * Magento
 *
 **/
?>

<?php
$toplinks_dropdown = true;
$search_dropdown   = false;
$theme = $this->helper('customlogo');
?>

<!-- Ajax Login -->
<div class="skip-links2"> <span class="skip-link2 skip-account2"></span></div>
<div id="header-account2" class="skip-content2"></div>
<!-- End Ajax Login -->
<!-- MENÚ LATERAL -->
<div id="header-nav" class="skip-content nav-content">
    <?php echo $this->getChildHtml('topMenu') ?>
</div>
<!-- END MENÚ LATERAL -->
<div id="menu-active"></div>
<div id="bag-active"></div>
<header id="header" class="page-header">

    <!--<div class="header-row-background">
        <div class="container">
            <div class="header-row">

                <div class="header-switchers">
                    <?php echo $this->getChildHtml('store_language') ?>
                    <?php echo $this->getChildHtml('currency_switcher') ?>
                </div>
                <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>

            </div>
        </div>
    </div>-->

    <div class="container">
        <div class="page-header-container">
            <!-- logo -->

            <div class="main-menu col-md-5 col-xs-4 col-lg-5" style="display:block;">
            		<!-- Menu Label -->
			        <a id="header-navBtn" class="skip-link skip-nav">
			            <span class="iconMenu"></span>
			            <!--<span class="label"><?php //echo $this->__('Menu'); ?></span>-->
			        </a>
                    
            </div>
            <div class="col-md-2 col-xs-4 col-lg-2 logo-container">
            <?php if ($theme->isEnabled()): ?>
                <?php if ($theme->getLogoType() == 'logo_images'): ?>
                    <?php if ($theme->getLogoUpload()): ?>
                        <a class="logo" href="<?php echo $this->getUrl('') ?>">
                            <img src="<?php echo Mage::getBaseUrl('media').'images/'.$theme->getLogoUpload(); ?>" alt="<?php echo $theme->getLogoAlt(); ?>" />
                        </a>
                    <?php endif ?>
                <?php elseif ($theme->getLogoType() == 'logo_text'): ?>
                    <h1 class="logo">
                        <a class="logo-link" href="<?php echo $this->getUrl('') ?>">
                            <?php echo $theme->getLogoDesc(); ?>
                        </a>
                    </h1>
                <?php endif ?>
            <?php else: ?>
                <a class="logo" href="<?php echo $this->getUrl('') ?>">
                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                </a>
            <?php endif ?>
            </div>
            <!-- end logo -->
            <div class="head_holder col-md-5 col-xs-4 col-lg-5">
                <!--<div class="cms-pages-marte">
                    <ul>
                        <li><a href="<?php echo Mage::getBaseUrl()."lab" ?>"><?php echo $this->__('Lab') ?></a></li>
                        <li><a href="<?php echo Mage::getBaseUrl()."about" ?>"><?php echo $this->__('About') ?></a></li>
                    </ul>
                </div>-->
                <!-- Top Links -->
                <div class="top-links">
                    <?php
                    $toplinksClass  = "top-links-inline";
                    $toplinksID     = "";
                    if($toplinks_dropdown):
                        $toplinksClass  = "skip-content";
                        $toplinksID     = "header-account-dropdown";
                        ?>
                        <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#<?php echo $toplinksID; ?>" class="skip-link account-dropdown">
                            <span class="label"></span>
                        </a>
                    <?php endif ?>

                    <div id="<?php echo $toplinksID; ?>" class="<?php echo $toplinksClass; ?>">
                    <!--?php echo $this->getChildHtml('topLinks') ?-->
                        <div class="links">
                        <ul>
                            <li onclick="<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) {?> abrirlogin() <?php } ?>"><a href="<?php echo Mage::getUrl('customer/account/login'); ?>" ><span><?php echo $this->__('Sign in') ?></span></a></li>
                            <li><a href=""><span><?php echo $this->__('Saved') ?></span></a></li>
                        </ul>
                        </div>

                    </div>
                    <div id="header-right">
                    	<div class="header-switchers">
		                    <?php echo $this->getChildHtml('store_language') ?>
		                    <?php //echo $this->getChildHtml('currency_switcher') ?>
		                </div>
                        <ul>
                            <li onclick="<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) {?> abrirlogin() <?php } ?>"><a class="menu-web" href="<?php echo Mage::getUrl('customer/account/login'); ?>"><span><?php echo $this->__('Sign in') ?></span></a></li>
                            <li><a class="menu-web" href=""><span><?php echo $this->__('Saved') ?></span></a></li>
                            <div class="header-minicart desktop">
                                <?php echo $this->getChildHtml('minicart_head'); ?>
                            </div>
                        </ul>
                    </div>
                </div>
                <!-- end Top Links -->

            </div>
            <!-- Search -->
            <div class="header-search desktop">
                <?php
                $searchClass  = "";
                $searchID     = "";
                if($search_dropdown):
                $searchClass  = "skip-content";
                $searchID     = "search-dropdown";
                ?>
                <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#<?php echo $searchID; ?>" class="skip-link account-dropdown">
                    <span class="label"><?php echo $this->__('Search'); ?></span>
                </a>
                <div id="<?php echo $searchID; ?>" class="<?php echo $searchClass; ?>">
                    <?php endif ?>

                    <?php echo $this->getChildHtml('topSearch') ?>

                    <?php if($search_dropdown): ?>
                </div>
            <?php endif ?>
            </div>
            <!-- end Search -->
        </div>
    </div>



    <?php echo $this->getChildHtml('topContainer'); ?>

    <?php require_once("mobile-panel.phtml"); ?>
</header>
<?php echo $this->getChildHtml('header_slider'); ?>