<?php
/**
 * Magento
 *
**/
?>

<!-- *************  Skip Container for Mobile ************* -->    
<div class="skip-container mobile">
    <div class="container">
        <div id="links-header" class="skip-links">        
            <!-- Menu Label -->
            <a href="#header-nav" class="skip-link skip-nav">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Menu'); ?></span>
            </a>
        
            <!-- Search Label -->
            <a href="#header-search" class="skip-link skip-search">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Search'); ?></span>
            </a>
            <!-- Search content -->
            <div id="header-search" class="skip-content">
                <?php echo $this->getChildHtml('topSearch') ?>
            </div>
        
            <!-- Account Label -->
            <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#header-account" class="skip-link skip-account">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Account'); ?></span>
            </a>
            <!-- Account content -->
            <div id="header-account" class="skip-content">
                    <div id="mobile-menu">
                        <?php echo $this->getChildHtml('topMenu') ?>
                        <?php echo $this->getChildHtml('topLinks') ?>
                    </div>
                    <div id="mobile-menu2">
                        <ul>
                            <a href="https://www.facebook.com/wearingmarte/" target="_blank"><li>Facebook</li></a>
                            <a href="https://www.instagram.com/wearingmarte/" target="_blank"><li>Instagram</li></a>
                            <a href="https://twitter.com/wearingmarte" target="_blank"><li>Twitter</li></a>
                        </ul>
                    </div>
                    <div id="mobile-menu3">
                        <ul>
                            <li onclick="<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) {?> abrirlogin() <?php } ?>"><a class="menu-web" href="<?php echo Mage::getUrl('customer/account/login'); ?>"><span><?php echo $this->__('Sign in') ?></span></a></li>
                            <li><a class="menu-web" href=""><span><?php echo $this->__('Saved') ?></span></a></li>
                        </ul>
                    </div>
            </div>
            <!-- Logo -->
            <a class="logo" href="<?php echo Mage::getBaseUrl(); ?>">          
                <div><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></div>
            </a>
            <!-- Cart -->
            <div class="header-minicart mobile">
                <?php echo $this->getChildHtml('minicart_head_mobile'); ?>
            </div>
        </div> 
    </div>
</div>
<!-- *************  End Skip Container ************* -->