	<div class="page-title">
		<h1><?php echo $this->__("RMA Details"); ?></h1>
	</div>
<?php	$id = $this->getRequest()->getParam("id");
    /** @var Webkul_RmaSystem_Model_Rma $this_rma */
    $this_rma = $this->getRmaDetails($id);																		?>
	<form method="post" action="<?php echo $this->getUrl('rmasystem/index/updaterma/'); ?>" id="wk_rma_con_form" enctype="multipart/form-data">
	<div class="dashboard">
		<div class="box-account box-info wk_rma_bigbox">
			<div class="wk_rma_print_actions">
			<?php
			$orderItemsPro=Mage::getModel('rmasystem/items')->getCollection()->addFieldToFilter('rma_id',$this_rma->getId()); 
			$wrong_product_type='';
			if(count($orderItemsPro)==1){
				foreach ($orderItemsPro as $item_pro) {
					$item_pro_data=Mage::getModel("sales/order_item")->load($item_pro->getItemId());
					if($item_pro_data->getProductType()=='downloadable' || $item_pro_data->getProductType()=='virtual')
						$wrong_product_type='invalid';
				}
			}
			?>
<?php 			if($this_rma->getShippingLabel() > 0 && $this_rma->getResolutionType() !== 0 && $wrong_product_type=='')	{ 															?>
					<a class="link-print" onclick="this.target='_blank';" href="<?php echo $this->getUrl('rmasystem/index/printlabel/',array('id'=>$id)); ?>"><?php echo $this->__("Print Shipping Label"); ?></a>&nbsp;|&nbsp;
<?php 			}																									?>
				<?php if($this_rma->isWaitingShipment()): ?>
					<div>
						<a href="<?= $this_rma->getLabelUrl() ?>" target="_blank"><?= $this->__('Print Label') ?></a>
					</div>
				<?php endif; ?>
			</div>
			<div class="col2-set">
			    <div class="col-1">
			        <div class="box">
			            <div class="box-title">
			                <h3><?php echo $this->__("Order Id"); ?></h3>
			            </div>
			            <div class="box-content">
			                <p><a href="<?php echo $this->getUrl('sales/order/view/').'order_id/'.$this_rma->getOrderId(); ?>">#<?php echo $this_rma->getIncrementId();?></a></p>
			            </div>
			        </div>
			    </div>
		        <div class="col-2">
			        <div class="box">
			            <div class="box-title">
			                <h3><?php echo $this->__("Status"); ?></h3>
			            </div>
			            <div class="box-content">
                            <strong><?= $this_rma->getStatusText(true) ?></strong>
			            </div>
			        </div>
	            </div>
		    </div>
		    <div class="col2-set">
			    <!--<div class="col-1">
			        <div class="box">
			            <div class="box-title">
			                <h3><?php echo $this->__("Package Condition"); ?></h3>
			            </div>
			            <div class="box-content">
<?php 						if($this_rma->getPackageCondition() == 0)
			                	echo "<p><b>".$this->__("Open")."</b></p>";
			                else
			                	echo "<p><b>".$this->__("Packed")."</p>";											?>
			            </div>
			        </div>
			    </div>-->
		        <div class="col-1">
			        <div class="box">
			            <div class="box-title">
			                <h3><?php echo $this->__("Resolution Type"); ?></h3>
			            </div>
			            <div class="box-content">
<?php 						if($this_rma->getResolutionType() == 0)
			                	echo "<p><b>".$this->__("Refund")."</b></p>";
			                else
			                	echo "<p><b>".$this->__("Exchange")."</b></p>";										?>
			            </div>
			        </div>
	            </div>
				<div class="col-2">
					<div class="box">
						<div class="box-title">
							<h3><?php echo $this->__("Created On"); ?></h3>
						</div>
						<div class="box-content">
							<p><?php echo date("Y-m-d g:i:s a", Mage::getModel('core/date')->timestamp($this_rma->getCreatedAt())); ?></p>
						</div>
					</div>
				</div>
		    </div>
	    </div>
	    <h2 class="table-caption"><?php echo $this->__("Item(s) Requested for RMA"); ?></h2>
	    <table class="data-table">
		    <thead>
		        <tr>
		            <th><?php echo $this->__("Product Name"); ?></th>
		            <th><?php echo $this->__("SKU"); ?></th>
                    <?php if($this_rma->isSizeExchange()): ?>
						<th><?= $this->__('Original Size') ?></th>
						<th><?= $this->__('New Size') ?></th>
					<?php endif; ?>
		            <!--<th class="a-right"><?php echo $this->__("Return Qty"); ?></th>
		            <th class="a-right"><?php echo $this->__("Reason"); ?></th>-->
		            <th class="a-right"><?php echo $this->__("Price"); ?></th>
		        </tr>
		    </thead>
<?php 	$orderItems = Mage::getModel("rmasystem/items")->getCollection()->addFieldToFilter("rma_id",$id);
		/** @var Webkul_RmaSystem_Model_Items $item */
foreach($orderItems as $item)	{
			$helper = Mage::helper('rmasystem');
            /** @var Mage_Sales_Model_Order_Item $mage_item */
            $mage_item = Mage::getModel("sales/order_item")->load($item->getItemId());
            if($simpleItem = $helper->getLinkedSimpleItem($mage_item))
            {
                $mage_item = $simpleItem;
            }
			$product = Mage::getModel("catalog/product")->load($mage_item->getProductId());							?>
    		<tbody>
	            <tr class="border">
				    <td><h3 class="product-name"><?php echo $product->getName(); ?></h3></td>
				    <td><?php echo $product->getSku(); ?></td>
					<?php if($this_rma->isSizeExchange()): ?>
						<?php $requestedProduct = Mage::getModel('catalog/product')->load($item->getRequestedProductId()); ?>
						<td><?= $product->getAttributeText('size') ?></td>
						<td><?= $item->getRequestedProductSize() ?></td>
					<?php endif; ?>
				    <!--<td class="a-right"><?php echo $item->getQty(); ?></td>
				    <td class="a-right"><?php echo Mage::getModel("rmasystem/reason")->load($item->getReasonId())->getReason(); ?></td>-->
                    <td class="a-right"><?= Mage::helper('core')->formatCurrency($product->getPrice()) ?></td>
				</tr>
            </tbody>
<?php 	}																											?>
        </table>
	</div>
	<div id="wk_rma_conversation_container">
<?php
	 	$collection = $this->getCollection();
	 	$customer_id = Mage::getSingleton("customer/session")->getId();
        foreach ($collection as $eachconver) {					       												?>
        	<div class="wk_rma_onereply">
		        <span class="wk_rma_onereply_head <?php if($eachconver->getSender() == $customer_id) echo "wk_rma_onereply_customer";?>">
		            <span class="wk_rma_onereply_head_left"><?php echo date("Y-m-d g:i:s a", Mage::getModel('core/date')->timestamp($eachconver->getCreatedAt())); ?></span>
					<span class="wk_rma_onereply_head_right"><?php if($eachconver->getSender() == $customer_id) echo $this->__("Me");else echo $this->__("Admin"); ?></span>
		        </span>
		        <p class="wk_rma_onereply_cntnt"><?php echo nl2br(strip_tags($eachconver->getMessage())); ?></p>
		    </div>
<?php   } ?>
    		<input type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" name="form_key"/>
    		<input type="hidden" value="<?php echo $id; ?>" name="rma_id"/>
	        <h2 class="legend wk_rma_clear"><?php echo $this->__("Send Message"); ?></h2>
	        <ul class="form-list">
	            <li class="wide">
	                <label class="required"><em>*</em><?php echo $this->__("Enter Message"); ?></label>
	                <div class="input-box">
	                    <textarea class="required-entry" name="message" id="wk_rma_additional_info"></textarea>
	                </div>
	            </li>
<?php 		if($this_rma->isOpen())	{																		?>
	            <li class="wide">
        			<label for="wk_rma_solved" class="wk_rma_agree_label">
						<input type="checkbox" name="solved" id="wk_rma_solved"/>
<?php 					echo $this->__("Check To mark as solved"); 													?>
        			</label>
        		</li>
<?php 		} ?>
	        </ul>
		    <a href="<?php echo $this->getUrl('rmasystem/')?>">&laquo;<?php echo $this->__("back"); ?></a>
		    <div class="buttons-set">
		        <p class="required">* <?php echo $this->__("Required Fields"); ?></p>
		        <button class="button" title="<?php echo $this->__("Submit Request"); ?>" type="submit">
		        	<span><?php echo $this->__("Send Message"); ?></span>
		        </button>
		    </div>
		</form>
	</div>
<script type="text/javascript">
	new VarienForm("wk_rma_con_form", true);
	function half_upload(this_input){
        jQueryRma("#wk_rma_add_images_container").find(".new_one").remove();
        for(var i=0; i<this_input.files.length; i++){
            if(this_input.files && this_input.files[i]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    jQueryRma("#wk_rma_add_images_container").append("<img class='wk_rma_add_images new_one' src='"+e.target.result+"'/>");
                }
                reader.readAsDataURL(this_input.files[i]);
            }
        }
    }
</script>