<?php
 /**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2016 GoMage (https://www.gomage.com)
 * @author       GoMage
 * @license      https://www.gomage.com/license-agreement/  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use
 * @version      Release: 5.9.2
 * @since        Class available since Release 4.0
 */ 
?>
<?php $discount_position = Mage::helper('gomage_checkout')->getConfigData('general/enable_discount'); ?>
<?php if($discount_position == 1): ?> 
	<?php echo $this->getChildHtml('discount'); ?>
	<?php echo $this->getChildHtml('giftcards'); ?>
<?php endif; ?>
<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
    <table class="data-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        
		<?php if(Mage::helper('gomage_checkout')->getConfigData('general/allow_remove')>0):?>
		<col width="1" />				
		<?php endif;?>
		
		<?php if(Mage::helper('gomage_checkout')->getConfigData('address_fields/thumbnails')>0):?>
		<col width="1" />				
		<?php endif;?>
				
		<col />
		
		<?php if(Mage::helper('gomage_checkout')->getConfigData('gift_wrapping/enable')>0):?>
		<col width="1"/>
		<?php endif; ?>
		
        <col width="1" />
		<?php if(Mage::helper('gomage_checkout')->getConfigData('general/allow_change_qty')>0):?>
        <col width="50" />
		<?php else:?>
		<col width="1"/>
		<?php endif;?>
		
		<col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody >
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>          
    <?php echo $this->getChildHtml('items_after'); ?>            
</div>
<?php if($discount_position == 2): ?>
<div class="discount-bottom">
	<?php echo $this->getChildHtml('discount'); ?>
	<?php echo $this->getChildHtml('giftcards'); ?>
</div>
<?php endif;?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
