<?php
/** @var Webkul_RmaSystem_Block_Adminhtml_Rma_New_Renderer_Orderitems_Block $this */
?>
<div class="grid">
    <table class="order-items-table">
        <thead>
        <tr class="headings">
            <th><label><input type="checkbox" class="check_all"></label></th>
            <th>SKU</th>
            <th>Nombre</th>
            <th>Unid.</th>
            <th class="size-cell">Talla original</td>
            <th class="size-cell">Nueva talla</td>
            <th class="qty-cell">Devolver</th>
            <th>Precio</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->getOrderItems() as $item) { ?>
        <tr>
            <td>
                <label>
                    <input
                        type="checkbox"
                        class="item-checkbox"
                        name="item_checked[<?= $item->getId() ?>]"
                        data-item-id="<?= $item->getId() ?>"
                        data-item-name="<?= $item->getProduct()['name'] ?>"
                    >
                </label>
                <input
                    type="hidden"
                    name="item_reason[<?= $item->getId() ?>]"
                    value="<?= Webkul_RmaSystem_Model_Constants::ReasonDefault ?>"
                    >
            </td>
            <td><?= $item->getProduct()->getSku() ?></td>
            <td><?= $item->getProduct()->getName() ?></td>
            <td><?= $this->getQtyAvailableForRefund($item) ?></td>
            <td class="size-cell"><?= $this->getItemSize($item) ?></td>
            <td class="size-cell">
                <label>
                    <select id="requested_size_<?= $item->getId() ?>" name="requested_size[<?= $item->getId() ?>]" style="width: auto;" disabled>
                        <option value="">(No cambiar)</option>
                        <?php foreach ($this->getHelper()->getOtherAvailableSizes($item) as $size)
                        { ?>
                            <option value="<?= $size->getProductId() ?>"><?= $size->getDescription() ?></option>
                        <?php } ?>
                    </select>
                </label>
            </td>
            <td class="qty-cell">
                <label>
                    <input type="number" id="return_item_<?= $item->getId() ?>" name="return_item[<?= $item->getId() ?>]" min="1" max="<?= $this->getQtyAvailableForRefund($item) ?>" value="<?= $this->getQtyAvailableForRefund($item) ?>" disabled>
                </label>
            </td>
            <td><?= $this->getFormattedPrice($item) ?></td>
        </tr>
        </tbody>
        <?php } ?>
    </table>
</div>

<style type="text/css">
    .size-cell, .qty-cell
    {
        display: none;
    }
    .columns .form-list td.value
    {
        width: auto;
    }
    .order-items-table input[type=number]
    {
        font: 12px/1.5em Arial, Helvetica, sans-serif;
        width: 40px;
    }
    .order-items-table tbody td
    {
        vertical-align: middle;
    }
</style>
